language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed idristheunique/udagram-api-feed:v8
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user idristheunique/udagram-api-user:v8
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend idristheunique/udagram-frontend:v8
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy idristheunique/reverseproxy:v8

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push idristheunique/udagram-api-feed:v8
  - docker push idristheunique/udagram-api-user:v8
  - docker push idristheunique/udagram-frontend:v8
  - docker push idristheunique/reverseproxy:v8